services:
  server:
    build: ./back
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  client:
    build:
      context: ./front
    ports:
      - '8080:8080'
    networks:
      - app-network

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - '5432:5432'

    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d test']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db-data:

networks:
  app-network:
    driver: bridge